set-option -g set-titles on
set-option -g allow-rename on
set-option -g default-terminal screen.xterm-256color
set-option -g status-style bg=brightblack,fg=black
set-option -g default-shell /usr/bin/zsh
set-option -g destroy-unattached on
set-option -g mouse on
set-option -g status-right "#[fg=red,bright]#(~/bin/tmux-mail.sh) #[fg=white,bright,bg=black]#(~/bin/tmux-free-c-drive.sh)🖴#[fg=yellow,bright,bg=brightblack]#(grep SwapFree: /proc/meminfo | awk '{print $2/1024**2}')GB #[fg=orange,bright]#(~/bin/tmux-mem-cpu-load -a 1 -g 0)"
set-option -g status-interval 5
set-option -g history-limit 10000
