set-option -g set-titles on
set-option -g allow-rename on
set-option -g default-terminal screen.xterm-256color
set-option -g status-style bg=brightblack,fg=black
set-option -g default-shell /usr/bin/zsh
#set-option -g destroy-unattached on
set-option -g mouse on
set-option -g visual-bell on
set-option -g status-right "#[fg=brightwhite,bg=brightblack]#(~/bin/tmux-mail.sh) #[fg=blue,bg=terminal]#(~/bin/tmux-free-c-drive.sh)💾#[fg=black,bg=brightblack]#(~/bin/tmux-mem-cpu-load.sh -a 1 -g 0) #[fg=black,bg=brightblack]#(~/bin/tmux-free-swap.sh)𝌡"
set-option -g status-interval 5
set-option -g history-limit 10000
